//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inpe.Subord.Comav.Egse.Smc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public Settings()
        {
            this["ReportsConnectionString"] = "file name = " +
                                             this["db_connection_string"];
        }


        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\connection.udl")]
        public string db_connection_string {
            get
            {
                return ((string)(this["db_connection_string"]));
            }
            set
            {
                this["db_connection_string"] = value;

                // codigo adicionado abaixo:
                this["ReportsConnectionString"] = "file name = " +
                                             this["db_connection_string"];
            }

        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string tc_file_export_default_path {
            get {
                return ((string)(this["tc_file_export_default_path"]));
            }
            set {
                this["tc_file_export_default_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string tm_file_import_default_path {
            get {
                return ((string)(this["tm_file_import_default_path"]));
            }
            set {
                this["tm_file_import_default_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string sql_queries_default_path {
            get {
                return ((string)(this["sql_queries_default_path"]));
            }
            set {
                this["sql_queries_default_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string layouts_default_path {
            get {
                return ((string)(this["layouts_default_path"]));
            }
            set {
                this["layouts_default_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string flight_sw_file_path {
            get {
                return ((string)(this["flight_sw_file_path"]));
            }
            set {
                this["flight_sw_file_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string file_send_data_path {
            get {
                return ((string)(this["file_send_data_path"]));
            }
            set {
                this["file_send_data_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string file_save_path {
            get {
                return ((string)(this["file_save_path"]));
            }
            set {
                this["file_save_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frames_log_file_path {
            get {
                return ((string)(this["frames_log_file_path"]));
            }
            set {
                this["frames_log_file_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string tm_file_received_data {
            get {
                return ((string)(this["tm_file_received_data"]));
            }
            set {
                this["tm_file_received_data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string open_tc_file {
            get {
                return ((string)(this["open_tc_file"]));
            }
            set {
                this["open_tc_file"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("File Name=D:\\\\INPE\\COMAV_EGSE\\SMC\\connection_comav.udl")]
        public string ReportsConnectionString {
            get {
                return ((string)(this["ReportsConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ComavPadrao</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection db_connections_names {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["db_connections_names"]));
            }
            set {
                this["db_connections_names"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>C:\\INPE\\COMAV_EGSE\\SMC\\connection_comav.udl</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection db_connections_strings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["db_connections_strings"]));
            }
            set {
                this["db_connections_strings"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Ao modificar esses Settings pela interface grafica do VStudio, verificar se o codigo do construtor (com a reconfiguracao do acesso a base) nao foi apagado pelo editor grafico. Caso tenha sido apagado, recuperar o codigo deste construtor a partir do repositorio.")]
        public string ATENCAO_ATENCAO {
            get {
                return ((string)(this["ATENCAO_ATENCAO"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3001")]
        public string cortex_control_data_port {
            get {
                return ((string)(this["cortex_control_data_port"]));
            }
            set {
                this["cortex_control_data_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3070")]
        public string cortex_telemetry_data_port {
            get {
                return ((string)(this["cortex_telemetry_data_port"]));
            }
            set {
                this["cortex_telemetry_data_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3020")]
        public string cortex_telecommand_data_port {
            get {
                return ((string)(this["cortex_telecommand_data_port"]));
            }
            set {
                this["cortex_telecommand_data_port"] = value;
            }
        }
    }
}
